echo -e "Default \e[39mDefault"
echo -ne "\e[0m"
echo -e "Default \e[30mBlack"
echo -ne "\e[0m"


echo -e "Default \e[37mLight gray"
echo -ne "\e[0m"
echo -e "Default \e[90mDark gray"
echo -ne "\e[0m"
echo -e "Default \e[31mRed"
echo -ne "\e[0m"
echo -e "Default \e[91mLight red"
echo -ne "\e[0m"
echo -e "Default \e[32mGreen"
echo -ne "\e[0m"
echo -e "Default \e[92mLight green"
echo -ne "\e[0m"
echo -e "Default \e[33mYellow"
echo -ne "\e[0m"
echo -e "Default \e[93mLight yellow"
echo -ne "\e[0m"
echo -e "Default \e[34mBlue"
echo -ne "\e[0m"
echo -e "Default \e[94mLight blue"
echo -ne "\e[0m"
echo -e "Default \e[35mMagenta"
echo -ne "\e[0m"
echo -e "Default \e[95mLight magenta"
echo -ne "\e[0m"
echo -e "Default \e[36mCyan"
echo -ne "\e[0m"
echo -e "Default \e[96mLight cyan"
echo -ne "\e[0m"
echo -e "Default \e[97mWhite"
