#!/bin/bash
case $- in *i*) ;; *) return;; esac #GCA#
GINGER_HOME="${HOME}" #GCA#
source "${HOME}/.ginger/init" #GCA#

TZ='Europe/Warsaw'; export TZ
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# HISTORY behaviour
HISTCONTROL=ignorespace:ignoredups:erasedups
shopt -s histappend
HISTSIZE=-1
HISTFILESIZE=-1

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
shopt -s globstar

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

## todo debian based one ?
# if [ -f /etc/bash_completion ]
# then
#   . /etc/bash_completion
# fi

if [ -f /etc/bash_completion.d/gentoo-style-init ]
then
  . /etc/bash_completion.d/gentoo-style-init
fi

if [ -f "${HOME}/.config/user-dirs.dirs" ]
then
  . "${HOME}/.config/user-dirs.dirs"
fi

#############
# additions #

##############
## directories
if [[ -d ${HOME}/.cargo ]] && [[ -f ${HOME}/.cargo/env ]] ; then
  PATH="${PATH}:${HOME}/.cargo/env"
else
  echo "rust:cargo is not installed or env file is not present"
fi

if [[ -d ${HOME}/.bin ]] ; then
  PATH="${PATH}:${HOME}/.bin"
fi


##############
## binaries and functors

if type exa &>/dev/null ; then
  alias ls=exa
else
  echo "rust:exa is not installed"
fi

if type xcp &>/dev/null ; then
  alias cp=xcp
else
  echo "rust:xcp is not installed"
fi

if type lsd &>/dev/null ; then
  alias ll=lsd
else
  echo "rust:lsd is not installed"
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

if [[ -d ${HOME}/.pack/kitty/kitty ]] ; then
  PATH="${PATH}:${HOME}/.pack/kitty/kitty"
fi

. ${HOME}/.bash.z

_devshortprompt
